//USERS
export const USER_REGISTRATION = "USER_REGISTRATION";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR ";
export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_MY_PROFILE = "GET_MY_PROFILE";
export const GETTING_MY_PROFILE_ERROR = "GETTING_MY_PROFILE_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";

//PRODUCTS
export const FETCH_ALL_PRODUCTS = "FETCH_PRODUCTS";

//CUSTOMERS
export const FETCH_ALL_CUSTOMERS = "FETCH_ALL_CUSTOMERS";

//SALES
export const FETCH_ALL_SALES = "FETCH_ALL_SALES";
